
permalink: /posts/:categories/:year/:month/:day/:title.html
exclude: ["README.md", "changelog.md"]
highlighter: true

# Blog and Personal Info
title : Strongly Typed
tagline: Ramblings about programming languages
author :
  name : José Di Nunzio
  email : jose.dinuncio@gmail.com
  github : jdinunzio
#  twitter : notwitter
#  feedburner : nofeedname

production_url : http://jdinunzio.github.io

